site_name: Luca Vettori
theme:
  name: material
  favicon: images/favicon2.png
  logo: images/favicon2.png
  features:
    - navigation.tabs
  palette:
    # name: material
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/LucaV27
    - icon: fontawesome/brands/github
      link: https://github.com/LucaV27
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/lucavettori/
markdown_extensions:
  - attr_list
  - md_in_html
# Plugins
plugins:
  - search
  - blog
nav:
  - Home: index.md
#  - Publications:
#    - publications/index.md
  - Blog:
    - blog/index.md
  - Contact: contact.md
copyright: Copyright © 2025 Luca Vettori

